name : "M+とIPAの合成フォント"
url  : "http://mix-mplus-ipa.sourceforge.jp/"
license :
  type     : IPA
  filename :
    [
      "migu-README.txt",
      "IPAexfont00303/IPA_Font_License_Agreement_v1.0.txt"
    ]
